services:
  api:
    build: ./
    image: node:alpine
    command: sh -c "npm install && npm start"
    working_dir: /usr/app
    restart: always
    environment: 
      MODE: ${MODE}
      BASE_URL: ${BASE_URL}
      LANDING_URL: ${LANDING_URL}
      OWNER_URL: ${OWNER_URL}
      ECOMMERCE_URL: ${ECOMMERCE_URL}
 
      MONGO_URI: ${MONGO_URI}
      MONGO_URI_TEST: ${MONGO_URI_TEST}
      SALT_SECRET: ${SALT_SECRET}
      PORT: ${PORT}
 
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFE: ${JWT_LIFE}
      REFRESH_JWT_SECRET: ${REFRESH_JWT_SECRET}
      REFRESH_JWT_LIFE: ${REFRESH_JWT_LIFE}
 
      FILE_SERVER_URL: ${FILE_SERVER_URL}
      FILE_SERVER_HOST: ${FILE_SERVER_HOST}
      FILE_SERVER_PORT: ${FILE_SERVER_PORT}
      FILE_SERVER_USERNAME: ${FILE_SERVER_USERNAME}
      FILE_SERVER_PASSWORD: ${FILE_SERVER_PASSWORD}
      FILE_SERVER_ROOT_FILE_PATH: ${FILE_SERVER_ROOT_FILE_PATH}
 
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      BCC: ${BCC}
 
      GOOGLE_CAPTCHA_SECRET: ${GOOGLE_CAPTCHA_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
 
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE: ${TWILIO_PHONE}
      TWILIO_SITE_KEY: ${TWILIO_SITE_KEY}
 
      AI_NFT: ${AI_NFT}
      AI_NFT_DISTRO: ${AI_NFT_DISTRO}
 
      OWNER_ADDRESS: ${OWNER_ADDRESS}
      OWNER_PASSPHRASE: ${OWNER_PASSPHRASE}
      OWNER_PASSWORD: ${OWNER_PASSWORD}
 
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      
    ports:
      - "${PORT}:${PORT}"
    expose: 
      - "${PORT}"
    volumes:
      - ./:/usr/app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_URI: ${MONGO_URI}
      